version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

executors:
  node-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

jobs:
  bootstrap:
    executor: node-executor
    steps:
      - run: node --version
      - run: npm --version
      - run: yarn --version

      - checkout
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "yarn.lock" }}
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-

      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap

      - save_cache:
          paths:
            - node_modules
            - packages/postdfm/node_modules
            - packages/@postdfm/dfm2ast/node_modules
          key: node-{{ .Environment.CACHE_VERSION }}-depdendencies-{{ checksum "yarn.lock" }}

  compile:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "yarn.lock" }}
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-

      - run: yarn compile

      - persist_to_workspace:
          root: packages
          paths:
            - ./postdfm/dist
            - ./@postdfm/ast/dist
            - ./@postdfm/dfm2ast/dist
            - ./@postdfm/dfm2ast/src

  lint:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-{{ checksum "yarn.lock" }}
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-

      - attach_workspace:
          at: ~/repo/packages

      - run: yarn lint:check

  format:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-{{ checksum "yarn.lock" }}
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-

      - run: yarn format:check

  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-{{ checksum "yarn.lock" }}
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-

      - attach_workspace:
          at: ~/repo/packages

      - run: yarn test

      - store_test_results:
          path: test-results

      - codecov/upload:
          file: coverage/lcov.info

  release:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-{{ checksum "yarn.lock" }}
            - node-{{ .Environment.CACHE_VERSION }}-depdendencies-

      - attach_workspace:
          at: ~/repo/packages

      - run: yarn release

      - store_artifacts:
          path: ~/repo/dist
      - store_artifacts:
          path: ~/repo/package.json
      - store_artifacts:
          path: ~/repo/packages/@postdfm/ast/package.json
      - store_artifacts:
          path: ~/repo/packages/@postdfm/dfm2ast/package.json

workflows:
  version: 2
  ci:
    jobs:
      - bootstrap
      - compile:
          requires:
            - bootstrap
      - format:
          requires:
            - bootstrap
      - lint:
          requires:
            - compile
      - test:
          requires:
            - compile
      - release:
          requires:
            - lint
            - format
            - test
